<?php

namespace App\Services;

use App\Models\FeeStructure;
use App\Models\Invoice;
use App\Models\InvoiceLine;
use App\Models\Payment;
use App\Models\Student;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;

class FeeService
{
    /**
     * Generate an invoice for a student from the applicable fee structure.
     */
    public static function generateInvoiceForStudent(Student $student, FeeStructure $structure): Invoice
    {
        return DB::transaction(function () use ($student, $structure) {
            $subtotal = $structure->lines->sum('amount');

            $invoice = Invoice::create([
                'number' => SequenceService::next('invoice', 'INV'),
                'student_id' => $student->id,
                'parent_id' => $student->parent_id,
                'academic_year_id' => $structure->academic_year_id ?? $student->academic_year_id,
                'date' => now()->toDateString(),
                'due_date' => now()->addDays(15)->toDateString(),
                'subtotal' => $subtotal,
                'tax' => 0,
                'total' => $subtotal,
                'paid' => 0,
                'balance' => $subtotal,
                'state' => Invoice::STATE_OPEN,
            ]);

            foreach ($structure->lines as $line) {
                InvoiceLine::create([
                    'invoice_id' => $invoice->id,
                    'description' => $line->name,
                    'qty' => 1,
                    'unit_price' => $line->amount,
                    'amount' => $line->amount,
                ]);
            }

            return $invoice;
        });
    }

    /**
     * Generate invoices for all admitted students in a batch from the fee structure.
     */
    public static function generateInvoicesForBatch(FeeStructure $structure): int
    {
        return self::generateInvoicesForBatchWithInvoices($structure)->count();
    }

    /**
     * Generate invoices for a batch, returning the created invoices.
     */
    public static function generateInvoicesForBatchWithInvoices(FeeStructure $structure): Collection
    {
        $batchId = $structure->batch_id;
        $students = Student::where('state', Student::STATE_ADMITTED)
            ->when($batchId, fn ($q) => $q->where('batch_id', $batchId))
            ->whereDoesntHave('invoices', fn ($q) => $q->where('academic_year_id', $structure->academic_year_id))
            ->get();

        $created = collect();
        foreach ($students as $student) {
            $created->push(self::generateInvoiceForStudent($student, $structure));
        }

        return $created;
    }

    /**
     * Register a payment against an invoice and recompute paid/balance/state.
     */
    public static function registerPayment(Invoice $invoice, array $data): Payment
    {
        return DB::transaction(function () use ($invoice, $data) {
            if (! in_array($invoice->state, [Invoice::STATE_OPEN, Invoice::STATE_DRAFT])) {
                throw new \DomainException("Cannot pay invoice in state '{$invoice->state}'.");
            }

            $payment = Payment::create([
                'reference' => SequenceService::next('payment', 'PAY'),
                'invoice_id' => $invoice->id,
                'student_id' => $data['student_id'] ?? $invoice->student_id,
                'parent_id' => $data['parent_id'] ?? $invoice->parent_id,
                'amount' => $data['amount'],
                'method' => $data['method'],
                'gateway' => $data['gateway'] ?? null,
                'transaction_id' => $data['transaction_id'] ?? null,
                'state' => Payment::STATE_DONE,
                'date' => $data['date'] ?? now()->toDateString(),
            ]);

            $invoice->paid = $invoice->paid + $payment->amount;
            $invoice->balance = max(0, $invoice->total - $invoice->paid);
            if ($invoice->balance <= 0) {
                $invoice->state = Invoice::STATE_PAID;
            }
            $invoice->save();

            // Generate a receipt (PDF document is generated by a job/controller when storage is ready)
            ReceiptService::create($payment);

            // Refresh dashboard cached stats.
            cache()->forget('edubba:dashboard:stats');

            return $payment;
        });
    }

    /**
     * List of overdue invoices (balance > 0 and due_date < today).
     */
    public static function overdueInvoices(): Collection
    {
        return Invoice::where('state', Invoice::STATE_OPEN)
            ->where('balance', '>', 0)
            ->where('due_date', '<', now()->toDateString())
            ->get();
    }

    /**
     * Send a WhatsApp reminder to the parent about a pending invoice.
     * Uses the 'fee_reminder' template via NotificationService.
     */
    public static function sendInvoiceReminder(Invoice $invoice): bool
    {
        if (! in_array($invoice->state, [Invoice::STATE_OPEN, Invoice::STATE_DRAFT])) {
            return false;
        }

        $recipient = $invoice->parent?->mobile ?? $invoice->student?->parent?->mobile ?? $invoice->student?->mobile;
        if (! $recipient) {
            return false;
        }

        $body = sprintf(
            'تذكير بالرسوم: مستحق على الطالب %s مبلغ %s د.ع في فاتورة %s — نرجو السداد قبل %s.',
            $invoice->student?->full_name ?? '—',
            number_format($invoice->balance, 0),
            $invoice->number,
            $invoice->due_date?->format('Y/m/d') ?? '—'
        );

        NotificationService::send('whatsapp', $recipient, $body, $invoice->student, [
            'title' => 'تذكير بالرسوم',
            'template' => 'fee_reminder',
        ]);

        return true;
    }

    /**
     * Send an overdue alert (beyond grace period) for an invoice.
     */
    public static function sendOverdueAlert(Invoice $invoice): bool
    {
        if (! in_array($invoice->state, [Invoice::STATE_OPEN, Invoice::STATE_DRAFT])) {
            return false;
        }

        $recipient = $invoice->parent?->mobile ?? $invoice->student?->parent?->mobile ?? $invoice->student?->mobile;
        if (! $recipient) {
            return false;
        }

        $body = sprintf(
            'إنذار: فاتورة %s للطالب %s أصبحت متأخرة — المبلغ المتبقي %s د.ع. يرجى مراجعة إدارة المدرسة خلال ٧ أيام.',
            $invoice->number,
            $invoice->student?->full_name ?? '—',
            number_format($invoice->balance, 0)
        );

        NotificationService::send('whatsapp', $recipient, $body, $invoice->student, [
            'title' => 'رسوم متأخرة',
            'template' => 'fee_reminder',
        ]);

        return true;
    }

    /**
     * Send a "new invoice" WhatsApp to the parent after generation.
     */
    public static function sendNewInvoiceNotification(Invoice $invoice): bool
    {
        $recipient = $invoice->parent?->mobile ?? $invoice->student?->parent?->mobile ?? $invoice->student?->mobile;
        if (! $recipient) {
            return false;
        }

        $body = sprintf(
            'فاتورة جديدة رقم %s للطالب %s بمبلغ %s د.ع — تاريخ الاستحقاق %s.',
            $invoice->number,
            $invoice->student?->full_name ?? '—',
            number_format($invoice->total, 0),
            $invoice->due_date?->format('Y/m/d') ?? '—'
        );

        NotificationService::send('whatsapp', $recipient, $body, $invoice->student, [
            'title' => 'فاتورة جديدة',
            'template' => 'invoice_generated',
        ]);

        return true;
    }
}
